### ISSUE TITLE
Create a Python Game

### ISSUE THREAD

**Issue by Prouser123** [Prouser123/PyOS#22]
Challenge: Create a game in Python (e.g. Hangman or Snake) and submit a pull request for Hacktoberfest.

**Comment by ruchit2801** [comment]
I want to contribute to this issue. Please tell me if I am correct, 
(1) I will fork this repository
(2) I will clone it into my personal Computer
(3) I will add new directory named python_game
(4) Create a new python file which will be our python game
(5) Commit those changes
(6) Push the changes to my repo
(7) Make a pull request in GitHub

I am asking this because, I see in some issues, if someone has worked on that issue, their works is shown on that issue, but in my case, I am just making changes my way and pushing them, how people are supposed to know that I have solved a particular issue when I submit a pull request?
Thanks in advance

**Comment by Prouser123** [comment]
@ruchit2801 
When you submit a Pull Request, you can _refrence_ the issue by adding something like #22. Where the number after the `#` is the issue or pull request you would like to reference.

To contribute you can:

1. Fork this repository
2. Clone it to your computer
3. Create a new file in the `programs` directory for your python game (you might want to name it after the game that you are making)
4. Create your code
5. Commit and push your changes to your forked repo
6. Make a Pull Request on GitHub.

When creating your pull request, be sure to tick the `Allow edits from maintainers` box as it means I can commit to your fork to help with anything you might get stuck on.

Good Luck!

**Comment by ruchit2801** [comment]
Okay! What kind of game is supposed to be created. I mean game that can be played in terminal based on inputs and outputs from user( I learned one while learning python)?

**Comment by sinhaDroid** [comment]
Hello @Prouser123,

I have implemented a snake ladders game. Please have a look at # 30. let me know if you need any modification on the same.

**Comment by Prouser123** [comment]
Hacktoberfest 2018 has now ended. This issue will now be closed, but you are still free to work on this if you please.
